# Change these first
owner: paulwolters # Your GitHub organization or username, where this repository lives
repo: up # The name of this repository

sites:
  - name: BIH
    url: https://www.betoninhuis.nl
  - name: FIT-nl
    url: https://www.fit.nl
  - name: PB-nl
    url: https://www.parkerenbij.nl

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.wltrs.nl
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "Hier zie je de uptime status."
  introMessage: &copy; Paul 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
